
name: "Scrollbar"

web: "[mootools.net/forge/p/scrollbar](http://mootools.net/forge/p/scrollbar)"

description: "MooTools Scrollbar class, a Slider married with Fx.Scroll"

authors: "[Enrique Erne](http://mild.ch)"

license: "MIT License"

copyright: "&copy; 2010, Enrique Erne"

sources:
  - "Source/Meio.Mask.js"
  - "Source/Meio.Mask.Fixed.js"
  - "Source/Meio.Mask.Regexp.js"
  - "Source/Meio.Mask.Reverse.js"
  - "Source/Meio.Mask.Repeat.js"
  - "Source/Meio.Mask.Extras.js"

# Values for MooTools forge

author: tofu

current: 0.9.9

demo: http://www.mild.ch/productslider/

category: Interface

tags: [menu, slide, scroll, drag]

